"""
train_lstm_model.py
--------------------
Trains an LSTM model on sequences generated by generate_rich_sequences.py.

Saves sequence_model.h5 to ml/sequence_detection/ using absolute paths,
so this script can be run from anywhere in the repo:

  python ml/sequence_detection/train_lstm_model.py   ← works
  cd ml/sequence_detection && python train_lstm_model.py  ← also works

Prerequisites:
  Run generate_rich_sequences.py first to produce:
    processed_sequences.npy
    sequence_labels.npy
    label_mapping.json
    metadata.json
"""

import numpy as np
import json
from pathlib import Path

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import EarlyStopping

from sklearn.model_selection import train_test_split

# ── Resolve paths relative to THIS file, not cwd ─────────────────────────────

THIS_DIR = Path(__file__).resolve().parent

# ── Load sequences ────────────────────────────────────────────────────────────

seq_path   = THIS_DIR / "processed_sequences.npy"
label_path = THIS_DIR / "sequence_labels.npy"

if not seq_path.exists() or not label_path.exists():
    raise FileNotFoundError(
        "processed_sequences.npy or sequence_labels.npy not found.\n"
        "Run generate_rich_sequences.py first."
    )

X = np.load(seq_path)
y = np.load(label_path)

print(f"\nSequences loaded")
print(f"  X shape : {X.shape}")
print(f"  y shape : {y.shape}")

# ── Load label mapping ────────────────────────────────────────────────────────

with open(THIS_DIR / "label_mapping.json") as f:
    label_mapping = json.load(f)

# Derive num_classes from the actual labels present in y, not just len(label_mapping).
# If some classes are missing from the dataset, to_categorical would produce wrong
# one-hot vectors if we used len(label_mapping) blindly.
num_classes_from_mapping = len(label_mapping)
num_classes_from_data    = int(y.max()) + 1
num_classes              = max(num_classes_from_mapping, num_classes_from_data)

print(f"\nClasses in mapping : {num_classes_from_mapping}")
print(f"Classes in data    : {num_classes_from_data}")
print(f"Using num_classes  : {num_classes}")

if num_classes_from_mapping != num_classes_from_data:
    print(
        "WARNING: mismatch between label_mapping.json and actual labels in y.\n"
        "Some attack classes may be missing from your dataset CSVs.\n"
        "This is fine — the model will still train correctly."
    )

# ── One-hot encode labels ─────────────────────────────────────────────────────

y_cat = to_categorical(y, num_classes=num_classes)

# ── Train / test split ────────────────────────────────────────────────────────

X_train, X_test, y_train, y_test = train_test_split(
    X, y_cat,
    test_size=0.2,
    random_state=42
)

print(f"\nTrain samples : {len(X_train):,}")
print(f"Test  samples : {len(X_test):,}")

# ── Build LSTM model ──────────────────────────────────────────────────────────
# input_shape derived directly from X so it always matches the generated data.

seq_len      = X.shape[1]   # SEQUENCE_LENGTH from generate script
num_features = X.shape[2]   # number of feature columns

model = Sequential([
    LSTM(128, input_shape=(seq_len, num_features)),
    Dropout(0.3),
    Dense(64, activation="relu"),
    Dense(num_classes, activation="softmax"),
])

model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"],
)

model.summary()

# ── Train ─────────────────────────────────────────────────────────────────────

early_stop = EarlyStopping(
    monitor="val_loss",
    patience=3,
    restore_best_weights=True,
)

print("\nTraining LSTM model...\n")

history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=10,
    batch_size=64,
    callbacks=[early_stop],
)

# ── Evaluate ──────────────────────────────────────────────────────────────────

loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"\nTest accuracy : {accuracy * 100:.2f}%")
print(f"Test loss     : {loss:.4f}")

# ── Save model ────────────────────────────────────────────────────────────────

model_path = THIS_DIR / "sequence_model.h5"
model.save(str(model_path))
print(f"\nModel saved → {model_path}")

# ── Update metadata.json to stay in sync with this training run ───────────────
# This ensures investigation_agent.py always reads correct shape values.

meta_path = THIS_DIR / "metadata.json"
if meta_path.exists():
    with open(meta_path) as f:
        metadata = json.load(f)
else:
    metadata = {}

metadata["sequence_length"] = seq_len
metadata["num_features"]    = num_features
metadata["num_classes"]     = num_classes
metadata["test_accuracy"]   = round(accuracy * 100, 2)
metadata["test_loss"]       = round(loss, 4)

with open(meta_path, "w") as f:
    json.dump(metadata, f, indent=4)

print(f"metadata.json updated → {meta_path}")
print("\nDone. Run the agent pipeline next.")